---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iqfrizqe/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
    - /bin/chmod -R 755 $DEPLOYPATH
