
deployment:
  tasks:
    - export REPO_DIR=/home/xjuytzmt/repositories/grubri-farmsystem/grubri-farmsystem
    - cd $REPO_DIR
    - /usr/bin/rsync -av --delete ./ /home/xjuytzmt/public_html/
  hooks:
    postdeploy:
      - cd /home/xjuytzmt/public_html
      - mkdir -p tmp
      - touch tmp/restart.txt
